name: Continuous Delivery

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  

      - name: Create Stable Version Tag
        if: success() 
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S') 
          git tag "stable-v$VERSION"
          git push origin "stable-v$VERSION"
